version: "3.9"

services:
  nginx:
    image: docker.io/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./htpasswd:/etc/nginx/conf.d/htpasswd:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      dash:
        condition: service_healthy
  dash:
    build:
      context: ./
